version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: EwwSoggyTsukino
      POSTGRES_DB: points_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: AhMimisANo
    ports:
      - "5050:80"
