#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  ALTER DATABASE $APP_DB_NAME OWNER TO $APP_DB_USER;
  GRANT USAGE, CREATE ON SCHEMA PUBLIC TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  
   CREATE TABLE IF NOT EXISTS puser (
   	puser_id SERIAL PRIMARY KEY,
   	first_name varchar(200) NOT NULL,
   	last_name varchar(200)
   
   );
EOSQL
